directories:
  # clutter
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_CLUTTER_CD1/CLUTTER/15_DEG"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/clutter"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_CLUTTER_CD2/CLUTTER/15_DEG"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/clutter"

  # btr 60
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL1/SCENE1/BTR_60"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/btr60"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL1/SCENE1/BTR_60"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/btr60"

  # slicy
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/16_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/29_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/31_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/43_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/44_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/45_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/30_DEG/COL2/SCENE1/SLICY"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/slicy"

  # 2s1
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL2/SCENE1/2S1"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/2s1"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/45_DEG/COL2/SCENE1/2S1"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/2s1"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL2/SCENE1/2S1"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/2s1"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/30_DEG/COL2/SCENE1/2S1"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/2s1"

  # brdm 2
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL2/SCENE1/BRDM_2"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/brdm2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/45_DEG/COL2/SCENE1/BRDM_2"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/brdm2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/45_DEG/COL2/SCENE3/BRDM_2"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/brdm2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL2/SCENE1/BRDM_2"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/brdm2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/30_DEG/COL2/SCENE1/BRDM_2"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/brdm2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/30_DEG/COL2/SCENE3/BRDM_2"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/brdm2"

  # d7
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL2/SCENE1/D7"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/d7"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL2/SCENE1/D7"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/d7"

  # t62
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL2/SCENE1/T62"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t62"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL2/SCENE1/T62"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t62"

  # zil 131
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL2/SCENE1/ZIL131"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zil131"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL2/SCENE1/ZIL131"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zil131"

  # zsu 23-4
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/15_DEG/COL2/SCENE1/ZSU_23_4"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zsu234"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/45_DEG/COL2/SCENE1/ZSU_23_4"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zsu234"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD1/45_DEG/COL2/SCENE2/ZSU_23_4"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zsu234"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/17_DEG/COL2/SCENE1/ZSU_23_4"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zsu234"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/30_DEG/COL2/SCENE1/ZSU_23_4"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zsu234"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_MIXED_TARGETS_CD2/30_DEG/COL2/SCENE2/ZSU_23_4"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/zsu234"

  # t72
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A04"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A05"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A07"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A10"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A32"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A62"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A63"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/15_DEG/COL2/SCENE1/A64"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/45_DEG/COL2/SCENE1/A64"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD1/45_DEG/COL2/SCENE3/A64"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A04"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A05"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A07"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A10"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A32"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A62"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A63"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/17_DEG/COL2/SCENE1/A64"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/30_DEG/COL2/SCENE1/A64"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_T_72_VARIANTS_CD2/30_DEG/COL2/SCENE3/A64"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/t72"

  # mstar public chips (train test slicy)
  # slicy
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/SLICY/15_DEG"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/slicy"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/SLICY/30_DEG"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/slicy"

  # test targets
  # bmp2
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TEST/15_DEG/BMP2/SN_9563"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/test/bmp2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TEST/15_DEG/BMP2/SN_9566"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/test/bmp2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TEST/15_DEG/BMP2/SN_C21"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/test/bmp2"

  # btr70
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TEST/15_DEG/BTR70/SN_C71"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/test/btr70"

  # t72
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TEST/15_DEG/T72/SN_132"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/test/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TEST/15_DEG/T72/SN_812"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/test/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TEST/15_DEG/T72/SN_S7"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/test/t72"

  # train targets
  # bmp2
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TRAIN/17_DEG/BMP2/SN_9563"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/bmp2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TRAIN/17_DEG/BMP2/SN_9566"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/bmp2"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TRAIN/17_DEG/BMP2/SN_C21"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/bmp2"

  # btr70
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TRAIN/17_DEG/BTR70/SN_C71"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/btr70"

  # t72
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TRAIN/17_DEG/T72/SN_132"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TRAIN/17_DEG/T72/SN_812"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/t72"
  - load_path: "D:/MSTAR/MSTAR_PUBLIC_TARGETS_CHIPS_T72_BMP2_BTR70_SLICY/TARGETS/TRAIN/17_DEG/T72/SN_S7"
    save_path: "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/t72"
