directories:
  - "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/t72"
  - "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/bmp2"
  - "C:/Users/vlada/Desktop/Faks/SIAP/Project/images/public_chips/train/btr70"
